### ISSUE TITLE
Shell command exited with exit status 127 instead of 0.

### ISSUE THREAD

**Issue by Sl3dge78** [yukiarrr/ios-build-action#12]
Thank you for the action.
I'm having an issue, maybe you'll be able to help :

I use https://github.com/webbertakken/unity-builder to generate an iOs version of my project
then use your action to upload it to app store connect but get this error message :
`Shell command exited with exit status 127 instead of 0.`

Here's the full [log](https://pastebin.com/HVs0iMmN)

Any idea why it fails?
Thanks!

**Comment by yukiarrr** [comment]
Thanks for creating the Issue!
I have one question.
Which VMs are your workflows running on?(Linux, Mac, Windows, etc...)
I'd like to see your yaml.

**Comment by Sl3dge78** [comment]
Here's the full thing 

```
jobs:
  build-ios:
    name : Build IOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true
    
    - uses: actions/cache@v1.1.0
      with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: | 
            Library-${{ matrix.targetPlatform }}
            Library
            
    - uses: webbertakken/unity-builder@v1.1
      with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning : Semantic 
   
    - uses: yukiarrr/ios-build-action@v1.1.0
      with:
          project-path: build\iOS\iOS\Unity-iPhone.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: iOS Distribution
          certificate-password: ${{ secrets.P12_PASSWORD }}
          team-id: ${{ secrets.TEAM_ID }}
```

So running on ubuntu. I'll try on mac.

**Comment by yukiarrr** [comment]
Thanks!
That workflow runs on Linux, but can run iOS build only on Mac.
That's why you're getting an error.
However, if you change the VM to Mac, this time you get an error because [Unity Builder](https://github.com/webbertakken/unity-builder) cannot run on Mac.
There are two solutions to this problem.

- Split the job into Linux and Mac job
- Using [unity-build-action](https://github.com/yukiarrr/unity-build-action) instead of Unity Builder

### Split the job into Linux and Mac job
This is a method to run Unity build on Linux and iOS build on Mac.
In this case, you need to use Artifacts to pass files between jobs. (See [here](https://docs.github.com/en/actions/configuring-and-managing-workflows/persisting-workflow-data-using-artifacts#passing-data-between-jobs-in-a-workflow) for details)

```yaml
jobs:
  build-unity:
    name : Build Unity
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/cache@v1.1.0
      with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library

    - uses: webbertakken/unity-builder@v1.1
      with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning : Semantic

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact

  build-ios:
    name : Build iOS
    runs-on: macos-latest
    needs: build-unity
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: my-artifact
        path: path/to/artifact

    - uses: yukiarrr/ios-build-action@v1.1.0
      with:
          project-path: build\iOS\iOS\Unity-iPhone.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: iOS Distribution
          certificate-password: ${{ secrets.P12_PASSWORD }}
          team-id: ${{ secrets.TEAM_ID }}
```

### Using unity-build-action instead of Unity Builder
Unity Builder cannot run on Mac, but [unity-build-action](https://github.com/yukiarrr/unity-build-action) can build on Linux, Mac, Windows, and self-hosted.
Therefore, you can run Unity build and iOS build on the same job on Mac.

```yaml
jobs:
  build-ios:
    name : Build IOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - iOS
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        lfs: true

    - uses: actions/cache@v1.1.0
      with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}
            Library

    - uses: yukiarrr/unity-build-action@v0.6.0
      with:
          unity-version: ${{ env.UNITY_VERSION }}
          unity-username: ${{ secrets.UNITY_USERNAME }}
          unity-password: ${{ secrets.UNITY_PASSWORD }}
          unity-serial: ${{ secrets.UNITY_SERIAL }}
          build-target: ${{ matrix.targetPlatform }}

    - uses: yukiarrr/ios-build-action@v1.1.0
      with:
          project-path: Output/Unity-iPhone.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: iOS Distribution
          certificate-password: ${{ secrets.P12_PASSWORD }}
          team-id: ${{ secrets.TEAM_ID }}
```

Note that both methods use Mac, which consumes a lot of available time in GitHub Actions.
So, if you can, you might want to run them on self-hosted.
