### ISSUE TITLE
action building wrong scheme instead of the specified one

### ISSUE THREAD

**Issue by angelacassanelli** [yukiarrr/ios-build-action#121]
In my app I have two schemes: “appname-dev” and “appname”; I also have two different provisioning profiles: “appname.ios.dev” for the first one and “appname.ios.prod” for the second one.

I’ve set up the action to build “appname-dev” scheme, but it is building “appname” scheme instead. 

This is my action: 

```
      - name: Build the app
        uses: yukiarrr/ios-build-action@v1.11.0
        with:
            p12-base64: ${{ secrets.P12_BASE64 }}
            certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
            mobileprovision-base64: |
                ${{ secrets.MOBILEPROVISION_BASE64_PROD }}
                ${{ secrets.MOBILEPROVISION_BASE64 }}
            team-id: ${{ secrets.TEAM_ID }}
            project-path: appname/appname.xcodeproj
            workspace-path: appname/appname.xcworkspace
            scheme: appname-dev
            output-path: appname-dev.ipa
            export-options: ./appname/appname/Options.plist
            build-destination: generic/platform=iOS
            increment-version-number: patch
            increment-build-number: true
            bundle-identifier: appname.ios.dev
```

And this is my Option.plist:

```
<dict>
	<key>teamID</key>
	<string>*****</string>
	<key>signingStyle</key>
	<string>manual</string>
	<key>signingCertificate</key>
	<string>*****</string>
	<key>provisioningProfiles</key>
	<dict>
		<key>appname.ios.prod</key>
		<string>appname Prod Distribution</string>
		<key>appname.ios.dev</key>
		<string>appname Dev Distribution</string>
	</dict>
</dict>
```
