### ISSUE TITLE
No mapping provided

### ISSUE THREAD

**Issue by Raiden-16F7** [yukiarrr/ios-build-action#127]
I have two provisioning files one for Apple Development and one for Apple Distribution. but i get the following error

08:00:03]: ▸ Archive Succeeded
[08:00:03]: Generated plist file with the following values:
[08:00:03]: ▸ -----------------------------------------
[08:00:03]: ▸ {
[08:00:03]: ▸   "method": "ad-hoc"
[08:00:03]: ▸ }
[08:00:03]: ▸ -----------------------------------------
[08:00:03]: $ /usr/bin/xcrun /opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh -exportArchive -exportOptionsPlist '/var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/gym_config20240827-9130-pbeu2q.plist' -archivePath /Users/runner/Library/Developer/Xcode/Archives/2024-08-27/Nerve\ 2024-08-27\ 07.49.19.xcarchive -exportPath '/var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/gym_output20240827-9130-8ydvq8' 
+ xcodebuild -exportArchive -exportOptionsPlist /var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/gym_config20240827-9130-pbeu2q.plist -archivePath '/Users/runner/Library/Developer/Xcode/Archives/2024-08-27/Nerve 2024-08-27 07.49.19.xcarchive' -exportPath /var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/gym_output20240827-9130-8ydvq8
2024-08-27 08:00:05.201 xcodebuild[19764:67926] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path "/var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/Nerve_2024-08-27_08-00-05.188.xcdistributionlogs".
2024-08-27 08:00:06.032 xcodebuild[19764:67926] [MT] IDEDistribution: Command line name "ad-hoc" is deprecated. Use "release-testing" instead.
/opt/homebrew/lib/ruby/gems/3.0.0/gems/fastlane-2.222.0/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh: line 61: 19764 Segmentation fault: 11  xcodebuild "$@"
[08:00:12]: Exit status: 139

+----------------------------------------------+
|              Build environment               |
+---------------+------------------------------+
| xcode_path    | /Applications/Xcode_15.4.app |
| gym_version   | 2.222.0                      |
| export_method | ad-hoc                       |
| sdk           | iPhoneOS17.5.sdk             |
+---------------+------------------------------+

[08:00:12]: ▸ /Users/runner/work/NerveUpdatedApp/NerveUpdatedApp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'RNCClipboard' from project 'Pods')
[08:00:12]: ▸ /Users/runner/work/NerveUpdatedApp/NerveUpdatedApp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'RNCAsyncStorage' from project 'Pods')
[08:00:12]: ▸ /Users/runner/work/NerveUpdatedApp/NerveUpdatedApp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'RCT-Folly' from project 'Pods')
[08:00:12]: ▸ /Users/runner/work/NerveUpdatedApp/NerveUpdatedApp/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 11.0, but the range of supported deployment target versions is 12.0 to 17.5.99. (in target 'BVLinearGradient' from project 'Pods')
[08:00:12]: ▸ ** ARCHIVE SUCCEEDED **
[08:00:12]: 
[08:00:12]: ⬆️  Check out the few lines of raw `xcodebuild` output above for potential hints on how to solve this error
[08:00:12]: 📋  For the complete and more detailed error log, check the full log at:
[08:00:12]: 📋  /Users/runner/Library/Logs/gym/Nerve-Nerve.log
[08:00:12]: 
[08:00:12]: Looks like fastlane ran into a build/archive error with your project
[08:00:12]: It's hard to tell what's causing the error, so we wrote some guides on how
[08:00:12]: to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
[08:00:12]: Before submitting an issue on GitHub, please follow the guide above and make
[08:00:12]: sure your project is set up correctly.
[08:00:12]: fastlane uses `xcodebuild` commands to generate your binary, you can see the
[08:00:12]: the full commands printed out in yellow in the above log.
[08:00:12]: Make sure to inspect the output above, as usually you'll find more error information there
[08:00:12]: 
[08:00:12]: Looks like no provisioning profile mapping was provided
[08:00:12]: Please check the complete output, in particular the very top
[08:00:12]: and see if you can find more information. You can also run fastlane
[08:00:12]: with the `--verbose` flag.
[08:00:12]: Alternatively you can provide the provisioning profile mapping manually
[08:00:12]: https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up
+---------------------------------------------------------------------------------+
|                                  Lane Context                                   |
+---------------------------+-----------------------------------------------------+
| DEFAULT_PLATFORM          | ios                                                 |
| PLATFORM_NAME             | ios                                                 |
| LANE_NAME                 | ios export_ipa                                      |
| KEYCHAIN_PATH             | ~/Library/Keychains/ios-build.keychain              |
| ORIGINAL_DEFAULT_KEYCHAIN | "/Users/runner/Library/Keychains/login.keychain-db" |
+---------------------------+-----------------------------------------------------+
[08:00:12]: Called from Fastfile at line 199
[08:00:12]: ```
[08:00:12]:     197:	    end
[08:00:12]:     198:	
[08:00:12]:  => 199:	    build_app(
[08:00:12]:     200:	      workspace: use_workspace ? ENV['WORKSPACE_PATH'] : nil,
[08:00:12]:     201:	      project: !use_workspace ? ENV['PROJECT_PATH'] : nil,
[08:00:12]: ```
[08:00:12]: Error packaging up the application

My Workflow Setup
```
      - name: Build iOS
        uses: yukiarrr/ios-build-action@v1.12.0
        with:
          project-path: ios/Nerve.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: |
            ${{ secrets.MOBILEPROVISION_BASE64 }}
            ${{ secrets.DISTPROVISION_BASE64 }}
          code-signing-identity: |
            'Apple Development'
            'Apple Distribution'
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ios/Nerve.xcworkspace
          export-method: ad-hoc
          output-path: Nerve.ipa
          scheme: Nerve
          bundle-identifier: ${{ secrets.PRODUCT_BUNDLE_IDENTIFIER }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          configuration: 'Release'


```
