### ISSUE TITLE
Wrong path in 1.3.1 which works on 1.2.0

### ISSUE THREAD

**Issue by jerome-morgado** [yukiarrr/ios-build-action#37]
`
47 [17:54:35]: $ security import ios-build.p12 -k '/Users/runner/Library/Keychains/ios-build.keychain-db' -P '' -T /usr/bin/codesign -T /usr/bin/security -T /usr/bin/productbuild

48 [17:54:35]: ▸ 1 identity imported.

49 [17:54:36]: Setting key partition list... (this can take a minute if there are a lot of keys installed)

50 [17:54:36]: $ security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k 24553592-c311-4401-91f8-520d6290d743 **/Users/runner/Library/Keychains/ios-build.keychain-db** 1> /dev/null

51 [17:54:36]: ------------------------------------------

52 [17:54:36]: --- Step: install_provisioning_profile ---

53 [17:54:36]: ------------------------------------------

54[17:54:36]: Installing provisioning profile...

55 [17:54:36]: Failure to decode **/Users/runner/work/AAAAAAA/AAAAAAA/ios-build-1.mobileprovision**. Exit: 1: security: cert import failed: unknown error -1=ffffffffffffffff

security: problem decoding
`

The provisioning profile keychain is written into a folder then next script is looking for it in another folder which causes the error.
This work on release **1.2.0**

Regards

**Comment by yukiarrr** [comment]
@jerome-morgado Sorry for the late response.
Thanks for creating the Issue!
I'd like to see your yaml.

**Comment by jerome-morgado** [comment]
Hi,

I replaced my project name with **AAAAAAA**

```
name: "build-IPA"
on:
  pull_request:
  push:
    branches:
      - GHA
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - uses: yukiarrr/ios-build-action@v1.2.0
      with:
        project-path: AAAAAAA.xcodeproj
        p12-base64: ${{ secrets.CERTIFICAT_P12_BASE64 }}
#        p12-cer-base64: ${{ secrets.P12_CER_BASE64 }}
#        p12-key-base64: ${{ secrets.P12_KEY_BASE64 }}
#        certificate-password: ${{ secrets.CERTIFICATES_PASSWORD }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        export-method: "enterprise"
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        workspace-path: AAAAAAA.xcodeproj/project.xcworkspace
        disable-targets: 'AAAAAAA preprod,AAAAAAA dev,AAAAAAA qa,AAAAAAAUITests'
#        update-targets: "AAAAAAA"
#        export-options: ExportOptions.plist
        scheme: "AAAAAAA"

```
