### ISSUE TITLE
Exemple

### ISSUE THREAD

**Issue by jerome-morgado** [yukiarrr/ios-build-action#45]
Is it possible to have a working example or check the data before starting the action ?
It's hard to debug on GH side.

Here is my content 

BuildIPA.yaml file content  :

```
    # Doc : https://github.com/yukiarrr/ios-build-action
    - uses: yukiarrr/ios-build-action@v1.3.1
#      continue-on-error: true
      with:
        p12-base64: ${{ secrets.CERTIFICAT_P12_BASE64 }}
        certificate-password: ${{ secrets.CERTIFICATES_PASSWORD }}
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        project-path: DigitalSite2D.xcodeproj
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        workspace-path: DigitalSite2D.xcodeproj/project.xcworkspace
        scheme: "DigitalSite2D"
        update-targets: "DigitalSite2D"
        disable-targets: 'DigitalSite2D preprod,DigitalSite2D dev,DigitalSite2D qa,DigitalSite2DUITests'
        export-options: ExportOptions.plist
```

and ExportOptions.plist file content : 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>provisioningProfiles</key>
    <dict>
        <key>com.sixense.digitalsite</key>
        <string>DigitalSite Field</string>
    </dict>
	<key>destination</key>
	<string>export</string>
	<key>method</key>
	<string>enterprise</string>
	<key>generateAppStoreInformation</key>
	<true/>
	<key>stripSwiftSymbols</key>
	<true/>
	<key>teamID</key>
	<string>SIXENSE DIGITAL</string>
	<key>uploadBitcode</key>
	<true/>
	<key>uploadSymbols</key>
	<true/>
</dict>
</plist>
```

**Comment by jerome-morgado** [comment]
Maybe you could add an example of each Secrets in the documentation ?

**Comment by yukiarrr** [comment]
Thanks for the issue!

> Is it possible to have a working example or check the data before starting the action ?

See ["How to debug"](https://github.com/yukiarrr/ios-build-action/issues/42#issuecomment-757539769).

> error: No profile for team '***' matching 'Yousoon Field' found: Xcode couldn't find any provisioning profiles matching '***/Yousoon Field'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'Yousoon' from project 'Yousoon')

Can you build with the same team id and profile in Xcode?

**Comment by sayem314** [comment]
This works fine for me on a React Native project.

```yaml
name: iOS Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'ios/Appname.xcodeproj/project.pbxproj'

jobs:
  deploy:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Restore yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install

      - name: Install Pods
        working-directory: ios
        run: pod install --repo-update

      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.3.0
        with:
          project-path: ios/Obsess.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ios/Appname.xcworkspace
          scheme: Obsess
          output-path: Obsess.ipa

      - name: Upload IPA
        env:
          USER: ${{ secrets.APPSTORE_EMAIL }}
          PASS: ${{ secrets.UPLOAD_PASSWORD }}
        run: xcrun altool --upload-app -f "Obsess.ipa" -u "$USER" -p "$PASS"
        ```

**Comment by sayem314** [comment]
This works fine for me on a React Native project.

```yaml
name: iOS Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'ios/Appname.xcodeproj/project.pbxproj'

jobs:
  deploy:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Restore yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install

      - name: Install Pods
        working-directory: ios
        run: pod install --repo-update

      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.3.0
        with:
          project-path: ios/Appname.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ios/Appname.xcworkspace
          scheme: Obsess
          output-path: Obsess.ipa

      - name: Upload IPA
        env:
          USER: ${{ secrets.APPSTORE_EMAIL }}
          PASS: ${{ secrets.UPLOAD_PASSWORD }}
        run: xcrun altool --upload-app -f "Obsess.ipa" -u "$USER" -p "$PASS"
        ```

**Comment by sayem314** [comment]
This works fine for me on a React Native project.

```yaml
name: iOS Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'ios/Appname.xcodeproj/project.pbxproj'

jobs:
  deploy:
    name: Build IPA
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Restore yarn cache
        uses: c-hive/gha-yarn-cache@v1

      - name: Install Dependencies
        run: yarn install

      - name: Install Pods
        working-directory: ios
        run: pod install --repo-update

      - name: Build Archive
        uses: yukiarrr/ios-build-action@v1.3.0
        with:
          project-path: ios/Appname.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
          team-id: ${{ secrets.TEAM_ID }}
          workspace-path: ios/Appname.xcworkspace
          scheme: Appname
          output-path: Appname.ipa

      - name: Upload IPA
        env:
          USER: ${{ secrets.APPSTORE_EMAIL }}
          PASS: ${{ secrets.UPLOAD_PASSWORD }}
        run: xcrun altool --upload-app -f "Appname.ipa" -u "$USER" -p "$PASS"
        ```
