### ISSUE TITLE
How do I provide provisioning profiles for app-extensions?

### ISSUE THREAD

**Issue by sag333ar** [yukiarrr/ios-build-action#59]
This github workflow supports adding provisioning profile only for main app. I've multiple app-extensions like widget and siri-extensions. I would like to provide provisioning profiles for the same. How do I achieve that with this github work flow?

**Comment by yukiarrr** [comment]
Thanks for the issue!
Please check the following.

https://github.com/yukiarrr/ios-build-action#mobileprovision

> Base64 encoded mobileprovision file. If you want to specify multiple files, you need to input in multiple lines and then use _**export-options**_ to specify the provisioning profile to use for each executable in your app.

```yaml
- uses: yukiarrr/ios-build-action@v1.4.0
  with:
    mobileprovision-base64: |
      ${{ secrets.MY_MOBILEPROVISION_BASE64 }}
      ${{ secrets.YOUR_MOBILEPROVISION_BASE64 }}
```

or

```yaml
- uses: yukiarrr/ios-build-action@v1.4.0
  with:
    mobileprovision-path: |
      ios-build-1.mobileprovision
      ios-build-2.mobileprovision
```
