### ISSUE TITLE
Permission denied on MacOs

### ISSUE THREAD

**Issue by auriorx** [yukiarrr/ios-build-action#64]
Hi!

I was hoping you might've encountered the following error before and know how to fix it:

![image](https://user-images.githubusercontent.com/58956648/127437918-4c0a1792-bfc3-4360-8d2c-a7f23ffb7f0e.png)

I did try giving ruby some permissions, but that didn't seem to do the trick

Here's my YAML:

```
jobs:
  build-deploy-ios:
    runs-on: macos-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v2
      - name: Get Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Use cache
        uses: actions/cache@v2
        id: quasar-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-quasar-${{ hashFiles('**/package-lock.json') }}
      - name: Install Quasar (if uncached)
        if: steps.quasar-cache.outputs.cache-hit != 'true'
        run: |
          sudo npm install
          sudo npm install -g @quasar/cli 
          sudo npm install --unsafe-perm=true --allow-root          
          sudo npx quasar upgrade -i
          sudo npm install -g cordova
      - name: Placeholder replacements
        uses: mad9000/actions-find-and-replace-string@2
        with:
          source: ${{ github.ref }}
          find: "{{API_ENDPOINT}}"
          replace: ${{env.API_ENDPOINT}}
      - name: Install xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install cordova
        run: sudo npm install -g cordova
      - name: Quasar build
        run: sudo npx quasar build -m cordova -T ios --device --release --packageType="app-store"
      - name: Permissions
        run: sudo chown -R $(whoami) /Library/Ruby/Gems/*
      - name: Upload build output
        if: steps.quasar-cache.outputs.cache-hit != 'true'
        uses: actions/upload-artifact@v1
        with:
          name: project-experimental-ios
          path: ./dist/cordova/ios      
      - uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path: src-cordova/platforms/ios/project.xcodeproj
          p12-base64: ${{ env.APPLE_P12_CERT }}
          mobileprovision-base64: ${{ env.APPLE_MOBILE_PROVISION }}
          code-signing-identity: Apple Distribution
          team-id: ${{ env.APPLE_TEAM_ID }}
          scheme: project
          workspace-path: src-cordova/platforms/ios/project.xcworkspace
      - name: "Upload app to TestFlight"
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: "./dist/cordova/ios/project.ipa"
          issuer-id: ${{env.APPSTORE_ISSUER_ID}}
          api-key-id: ${{env.APPSTORE_API_KEY_ID}}
          api-private-key: ${{env.APPSTORE_API_PRIVATE_KEY}}

```

If not I'll be happy to check with fastlane, but I just thought I'd start here. 

Could you perhaps be of any help?

Thanks in advance.

~Auriorx
